language: python

python:
  - 3.7
  - 3.8

install:
  - pip install --upgrade pytest coverage codecov
  - python setup.py develop

script:
  - coverage erase
  - coverage run -m pytest -v

after_success:
  - coverage report
  - codecov
